3

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -32,11 +32,11 @@ jobs:
           -u $PRISMA_USER \
           -p $PRISMA_PASS \
           $MYREPO/$MYIMAGE:$TAG | tee result.out
-          e=`cat result.out | grep -c "threshold check results: FAIL"`
-          if [ $e -gt 100 ]; then
-            echo "Build failed"
-            exit 1
-          fi
+#          e=`cat result.out | grep -c "threshold check results: FAIL"`
+#          if [ $e -gt 100 ]; then
+#            echo "Build failed"
+#            exit 1
+#          fi
     - name: Push the Docker image
       run: |
         echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin docker.io
